name: Keep server alive

on: 
  workflow_dispatch:
  schedule:
    - cron: '*/14 * * * *'

jobs:
  ping_server: 
    runs-on: ubuntu-latest
    steps:
      - name: Ping server
        run: |
          curl -s https://expensewiseserver.onrender.com/
          echo "Pinged at $(date)"